# Generated by Django 5.1.3 on 2024-11-23 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradition',
            name='category',
        ),
        migrations.AddField(
            model_name='tradition',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradition',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
