# Generated by Django 5.1.3 on 2024-11-23 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_remove_tradition_category_tradition_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradition',
            name='event_day',
            field=models.DateField(default=datetime.date(2024, 11, 23)),
            preserve_default=False,
        ),
    ]
